name: Rust-Ubuntu

on:
  push:
    paths:
      - '**.rs'
      - 'Cargo.toml'
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.toml'
  schedule:
    - cron '0 0 * * 0'
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
