name: Rust-Windows

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      "**.yml"
      "**.rs"
      "Cargo.toml"
  pull_request:
    paths:
      "**.yml"
      "**.rs"
      "Cargo.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
